title: Carol Fontana
author: pro-panda
subtitle: Sharing DBA content and more!

url: "https://caroldacfontana.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://caroldacfontana.github.io/"
footer_text: "Theme by rhl-bthr"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"   
   link: "about"
 - name: "My Github"   
   absolute-link: "https://github.com/caroldacfontana"
 - name: "Resume-CV"
   absolute-link: "https://caroldacfontana.github.io/cv/"
