title: Carol Fontana
author: pro-panda
subtitle: Sharing DBA content and more!

url: "https://caroldacfontana.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://caroldacfontana.github.io/"
footer_text: "Theme by rhl-bthr"

profile-picture: assets/meme.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"   
   link: "about"
 - name: "My Github"   
   absolute-link: "https://github.com/caroldacfontana"
 - name: "My Linkedin"   
   absolute-link: "https://www.linkedin.com/in/carol-fontana-0a2b571ba/"

markdown: kramdown
highlighter: rouge
theme: minima
kramdown:
  input: GFM
  syntax_highlighter_opts:
    inline_theme: monokai
    line_numbers: false
